### ISSUE TITLE
Move client side source to this Repo

### ISSUE THREAD

**Issue by konekoya** [JJSPython/parseltongue#5]

**Comment by konekoya** [comment]
@wu87988622 I have added the client code into the `client` folder of t his repo. Could you have a look and see if it's okay? Thank you!

**Comment by konekoya** [comment]
I should create a PR first @@ sorry

**Comment by wu87988622** [comment]
OKOK
I will finish it today

**Comment by konekoya** [comment]
Running the django this morning, found out that I have to add my localhost to `ALLOWED_HOSTS` in settings.py. So it's now look like this `ALLOWED_HOSTS = ['vast-refuge-25114.herokuapp.com', '127.0.0.1']`. Is this Okay to commit this?

**Comment by wu87988622** [comment]
oh~ sorry I forget this
is ok commit `ALLOWED_HOSTS = ['vast-refuge-25114.herokuapp.com', '127.0.0.1']`
if you want run to localhost
you need change 

parselrongue/crawler/parser.py
` chrome_bin = os.environ.get('GOOGLE_CHROME_SHIM', None)`
`chrome_options = Options()`
            `chrome_options.binary_location = chrome_bin`
            `driver = webdriver.Chrome(chrome_options=chrome_options)`
to
`driver = webdriver.Chrome(executable_path=r'/chromedriver/chromedriver')`

because in the Heroku want use googleDriver need use Heroku buidpack 
(Heroku need add buidpack
https://github.com/heroku/heroku-buildpack-chromedriver.git,
https://github.com/heroku/heroku-buildpack-google-chrome.git)

but in the localhost use googleDriver need use localhot file /chromedriver/chromedriver

**Comment by konekoya** [comment]
Okay, I'll add these configs and see if it would work! Thanks for the reply!
